#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# Install nginx on your web-01
# server
# When querying Nginx at its root / with a GET request 
# (requesting a page) using curl, it must return a page that contains
# the string Hello World! Nginx should be listening on port 80
# You can’t use systemctl for restarting nginx

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

