#!/usr/bin/env bash
# How is the OSI model organized? 1. Alphabetically 2. From the lowest fo the highest level 3. Randomly

1. Application, Data Link, Network, Physical, Presentation, Session, Transport
2. Physical, Data Link, Network, Transport, Session, Presentation, Application
3. Network, Session, Application, Physical, Presentation, Data Link, Transport

