#!/usr/bin/env bash

1. Application, Data Link, Network, Physical, Presentation, Session, Transport
2. Physical, Data Link, Network, Transport, Session, Presentation, Application
3. Network, Session, Application, Physical, Presentation, Data Link, Transport
